version: "3.8"

services:
  localstack:
    container_name: "LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG=1
      - ENFORCE_IAM=0
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "localstack-vol:/tmp/localstack"
volumes:
  localstack-vol:
